# Generated by Django 5.1 on 2024-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='role',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cni',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
