# Generated by Django 5.1 on 2024-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_remove_candidature_role_alter_candidature_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cloture',
            field=models.BooleanField(default=False, verbose_name='Clôturer'),
        ),
        migrations.AddField(
            model_name='projet',
            name='remuneration',
            field=models.FloatField(default=0, verbose_name='Rémunération'),
        ),
    ]
