# Generated by Django 5.1 on 2024-09-03 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_projet_cloture_projet_remuneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='remuneration',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rémunération (en FCFA)'),
        ),
    ]
